#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x numlockx > /dev/null || numlockx &
xrandr --output DP-4 --scale 0.75x0.75

pgrep -x picom > /dev/null || picom &
#setxkbmap -layout "us,ru" -option grp:ctrl_space_toggle

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Window rules
bspc rule -a "Google-chrome" desktop=^2 state=fullscreen
bspc rule -a "Telegram-desktop" desktop=^1 state=floating rectangle=400x600+0+0

